replicaCount: 1

containers:
  image: 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-ecr-test
  tag: v0.4.1
  
ports:
  container_port: 5000
  lb_port: 80

deploymentAnnotations:
  secret.reloader.stakater.com/reload: postgres-secrets-manager
  
host: test.am
 
items:
  - name: POSTGRES_HOST
    yoursecret: postgres-secrets-manager
    key: POSTGRES_HOST

  - name: POSTGRES_PORT
    yoursecret: postgres-secrets-manager
    key: POSTGRES_PORT

  - name: POSTGRES_DATABASE
    yoursecret: postgres-secrets-manager
    key: POSTGRES_DATABASE

  - name: POSTGRES_USER
    yoursecret: postgres-secrets-manager
    key: POSTGRES_USER

  - name: POSTGRES_PASSWORD
    yoursecret: postgres-secrets-manager
    key: POSTGRES_PASSWORD

